
services:
  db:
    image: mysql:latest
    container_name: market-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306" # Mapeando a porta 3306 para acesso local
    volumes:
      - market-db-data:/var/lib/mysql # Volume persistente para dados
    networks:
      - market-network

volumes:
  market-db-data:
    driver: local

networks:
  market-network:
    driver: bridge
